# vim:filetype=sh

# if [[ -f "${HOME}/.bash_profile" ]]; then
# 	source "${HOME}/.bash_profile"
# fi
# if [[ -f "${HOME}/.config/wpg/wp_init.sh" ]]; then
# 	~/.config/wpg/wp_init.sh
# fi
# if [[ -f "${HOME}/.Xresources" ]]; then
# 	xrdb -merge -I$HOME "${HOME}/.Xresources"
# fi
# pwd | tee ~/vncpwd
cd "${HOME}"

if [[ -f "/etc/lightdm/Xsession" ]]; then
	exec /etc/lightdm/Xsession i3
else
	exec i3
fi
