#!/bin/bash
# For commands that should run before /vnc or /rdp.
# Runs after dotfiles are updated.

function ier() {
	#if exists, run.
	if [ -n "`which $1 2> /dev/null`" ]; then
		$@
	fi
}

#Not needed in ubuntu; only in arch
source /etc/profile.d/locale.sh

#Update Vim plugins and plugin manager
vim +MAINTAIN

#reload Xresources in case it was changed when dotfiles were updated.
ier xrdb ~/.Xresources

ier ~/.local/share/umake/bin/apm install file-icons highlight-selected jumpy language-docker script sort-lines
ier ~/.local/share/umake/bin/apm disable spell-check tree-view

export SHELL="bash"

export QT_QPA_PLATFORMTHEME="qt5ct"
export LANG="en_US.UTF-8"

#use this to check what contexts get env variables from this script. To check if they penetrate into i3 through vnc and/or rdp etc.
export RAN_REFRESH="YES"

