# colors

#WARNING: THIS FILE IS GENERATED BY WPGTK! EDIT THE ORIGINAL IN ~/.config/wpg/templates

darkest='212121'
red='d50000'
green='00c853'
yellow='ffd600'
blue='2962ff'
magenta='aa00ff'
cyan='00b8d4'
bright='bdbdbd'
dark='616161'
light_red='ff5252'
light_green='69f0ae'
light_yellow='ffff00'
light_blue='448aff'
light_magenta='e040fb'
light_cyan='18ffff'
brightest='eeeeee'

brighter='e0e0e0'
brightish='9e9e9e'
darkish='757575'
darker='424242'

accent='ff0000'
warning='ff00ff'
