# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'

# Colors
darkest='{color0}'
red='{color1}'
green='{color2}'
yellow='{color3}'
blue='{color4}'
pink='{color5}'
cyan='{color6}'
brighter='{color7}'
dark='{color8}'
accent='{color9}'
accent_lighter='{color10}'
warning='{color11}'
brown='{color12}'
darker='{color13}'
bright='{color14}'
brightest='{color15}'
