" vim:filetype=vim

let g:python_expected_path="/usr/bin/python"
let g:python2_expected_path="/usr/bin/python2"

source ~/.dot/l/vim/office/crowdai-pre-plugins
source ~/.dot/l/vim/plugins
source ~/.dot/l/vim/office/crowdai-post-plugins

set fileencodings=utf-8,cp936,gbk,utf-16le

if filereadable(python_expected_path)
  let g:python3_host_prog=python_expected_path
else
  let g:loaded_python3_provider=1 " disables Python 3 support
endif
if filereadable(python2_expected_path)
  let g:python_host_prog=python2_expected_path
else
  let g:loaded_python_provider=1 " disables Python 2 support
endif

set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
autocmd VimResized * wincmd = " Adjust split sizes when window resizes


set viminfo='10000,<10,:10000,%
if has('nvim')
  set viminfo+=n~/.history/nviminfo
else
  set viminfo+=n~/.history/viminfo
endif

set undofile
set undodir=~/.vim/undo

" Copies what was just pasted.
xnoremap p pgvy

com! -bar TOTABS call s:switch_to_tabs()

function! s:switch_to_tabs() abort
  set tabstop=4
  set noexpandtab
  set %retab!
endfunction

if exists("g:vimpager")
  let g:vimpager = {}
  let g:less = {}
  let g:vimpager.enabled = 1
  let g:vimpager.ansiesc = 1
  let g:less.enabled = 0 " disable less compatibility mode (re enable by pressing ,v)
  let g:vimpager.passthrough = 1 " passthrough text smaller than terminal height
  let g:less.scrolloff = 2
  set laststatus=0 " Not working.
  autocmd VimEnter * set laststatus=0
  set nomodifiable
  let g:vimpager_scrolloff = 2
else
  set mouse=a "To copy text like in every other program, need to hold shift when selecting it; which temporarily disables this setting.
  set laststatus=2 " Always display the statusline in all windows
  set showtabline=2 " Always display the tabline, even if there is only one tab
  nnoremap <Left> :echoe "Use h"<CR>
  nnoremap <Right> :echoe "Use l"<CR>
  nnoremap <Up> :echoe "Use k"<CR>
  nnoremap <Down> :echoe "Use j"<CR>
  set relativenumber
  set number
endif
