" vim:filetype=vim

set fileencodings=utf-8,cp936,gbk,utf-16le

set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
autocmd VimResized * wincmd = " Adjust split sizes when window resizes


set viminfo='10000,<10,:10000,%
set viminfo+=n~/.history/viminfo

set undofile
set undodir=~/.vim/undo

" Copies what was just pasted.
xnoremap p pgvy

com! -bar TOTABS call s:switch_to_tabs()

function! s:switch_to_tabs() abort
  set tabstop=4
  set noexpandtab
  set %retab!
endfunction

set mouse=a "To copy text like in every other program, need to hold shift when selecting it; which temporarily disables this setting.
set laststatus=2 " Always display the statusline in all windows
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>
set relativenumber
set number
