# vi:syntax=sh
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc) for examples

SHELL="/bin/bash"

# ssh/scp may still source bashrc in a noninteractive session; in a way that could seriously mess up file transfers.
if [[ "${NONINTERACTIVEBASHRC}" != "yes" ]]; then
	[[ "$-" != *i* ]] && return
fi


# History options
HISTCONTROL="ignoreboth" # don't put duplicate lines or lines starting with space in the history.
shopt -s histappend # append to the history file, don't overwrite it
shopt -s cmdhist # Save multi-line commands as one command
HISTFILE="${HOME}/.history/bash"
HISTSIZE=1000
HISTFILESIZE=2000000000
PROMPT_COMMAND='history -a' # Record each line as it gets issued


[[ "${DISPLAY}" ]] && shopt -s checkwinsize # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.

shopt -s autocd # cd automatically if dir is entered
#shopt -s dirspell # Correct spelling errors during tab-completion
#shopt -s cdspell # Correct spelling errors in arguments supplied to cd


PROMPT_DIRTRIM=2 # Automatically trim long paths in the prompt


bind "set completion-ignore-case on" # Perform file completion in a case insensitive fashion
#bind "set completion-map-case on" # Treat hyphens and underscores as equivalent
bind "set show-all-if-ambiguous on" # Display matches for ambiguous patterns at first tab press
bind "set mark-symlinked-directories on" # Immediately add a trailing slash when autocompleting symlinks to directories


# Enable incremental history search with up/down arrows (also Readline goodness)
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"Oc": forward-word'
bind '"Od": backward-word'

#shopt -s globsta # If set, the pattern "**" used in a pathname expansion context will match all files and zero or more directories and subdirectories.


# This defines where cd looks for targets. Add the directories you want to have fast access to, separated by colons.
# Ex: CDPATH=".:~:~/projects" will look for targets in the current working directory, in home and in the ~/projects folder
CDPATH="."

# This allows you to bookmark your favorite places across the file system. Define a variable containing a path and you will be able to cd into it regardless of the directory you're in
#shopt -s cdable_vars
# E.g.: export projects="$HOME/projects"


PS1='[\u@\h \W]\$ '

# set the title if using xterm
case "${TERM}" in
	xterm*|rxvt*)
		PS1="\[\e]0;\u@\h: \w\a\]${PS1}"
		;;
	*)	;;
esac

# enable color support for ls
if [[ -x /usr/bin/dircolors ]]; then
	[[ -r ~/.dircolors ]] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# enable programmable completion features
if ! shopt -oq posix; then
	if [[ -f /usr/share/bash-completion/bash_completion ]]; then
		source /usr/share/bash-completion/bash_completion
	elif [[ -f /etc/bash_completion ]]; then
		source /etc/bash_completion
	fi
fi

POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
powerline_shell_theme='custom_leftonly'
source /usr/share/powerline/bindings/bash/powerline.sh

source /usr/share/doc/pkgfile/command-not-found.bash

source "${HOME}/.dot/l/shrc/both"

