--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/patricol/.config/wpg/wallpapers/material.png"

-- Special
background="#212121"
foreground="#eeeeee"
cursor="#eeeeee"

-- Colors
color0="#212121"
color1="#d50000"
color2="#00c853"
color3="#ffd600"
color4="#2962ff"
color5="#aa00ff"
color6="#00b8d4"
color7="#bdbdbd"
color8="#616161"
color9="#ff5252"
color10="#69f0ae"
color11="#ffff00"
color12="#448aff"
color13="#e040fb"
color14="#18ffff"
color15="#eeeeee"
