# Shell variables
# Generated by 'wal'
wallpaper='/home/patricol/.config/wpg/wallpapers/material.png'

# Special
background='#212121'
foreground='#f5f5f5'
cursor='#f5f5f5'

# Colors
color0='#212121'
color1='#e53935'
color2='#43a047'
color3='#fdd835'
color4='#1e88e5'
color5='#d81b60'
color6='#00acc1'
color7='#e0e0e0'
color8='#616161'
color9='#ff0000'
color10='#ff5a36'
color11='#ff00ff'
color12='#6d4c41'
color13='#424242'
color14='#9e9e9e'
color15='#f5f5f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
