# Shell variables
# Generated by 'wal'
wallpaper='/home/patricol/.config/wpg/wallpapers/dummy.png'

# Special
background='#212121'
foreground='#eeeeee'
cursor='#eeeeee'

# Colors
color0='#212121'
color1='#d50000'
color2='#00c853'
color3='#ffd600'
color4='#2962ff'
color5='#aa00ff'
color6='#00b8d4'
color7='#bdbdbd'
color8='#616161'
color9='#ff5252'
color10='#69f0ae'
color11='#ffff00'
color12='#448aff'
color13='#e040fb'
color14='#18ffff'
color15='#eeeeee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
